# 1. Import Pandas

In [76]:
import pandas as pd

# 2. create dataframe

In [77]:
data = {
    'Name': ['abhay', 'aastik', 'aayush', 'aayushi', 'kohli', 'begum', 'anshika'],
    'Marks': [90, 78, 98, 89, 87, 88, 96],
    'Gender': ['Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female']}

In [78]:
data = pd.DataFrame(data)
data

      Name  Marks  Gender
0    abhay     90  Female
1   aastik     78  Female
2   aayush     98    Male
3  aayushi     89    Male
4    kohli     87    Male
5    begum     88    Male
6  anshika     96  Female

# 3. Display top 3 rows

In [79]:
data.head(3)

     Name  Marks  Gender
0   abhay     90  Female
1  aastik     78  Female
2  aayush     98    Male

# 4. Dispaly end 3 rows

In [80]:
data.tail(3)

      Name  Marks  Gender
4    kohli     87    Male
5    begum     88    Male
6  anshika     96  Female

In [81]:
data.shape

(7, 3)

In [82]:
data.describe()

           Marks
count   7.000000
mean   89.428571
std     6.528327
min    78.000000
25%    87.500000
50%    89.000000
75%    93.000000
max    98.000000

In [83]:
data.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [84]:
data.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

# 9. Find Unique values from Gender Coloumn

In [85]:
data['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

# 10. Find the no of unique value from gender coloumn

In [86]:
data.Gender.nunique()

2

# 11. Display count of unique values in gender coloumn

In [87]:
data.Gender.value_counts()

Gender
Male      4
Female    3
Name: count, dtype: int64

# 12. sort all the values from mark coloumn

In [88]:
data.Marks.sort_values()

1    78
4    87
5    88
3    89
0    90
6    96
2    98
Name: Marks, dtype: int64

In [89]:
# for descending
data.Marks.sort_values(ascending = False)

2    98
6    96
0    90
3    89
5    88
4    87
1    78
Name: Marks, dtype: int64

# 13. Find the total no of students marks btw 90 to 100

In [90]:
data['Marks']>=90

0     True
1    False
2     True
3    False
4    False
5    False
6     True
Name: Marks, dtype: bool

In [91]:
data['Marks'].between(90,100)

0     True
1    False
2     True
3    False
4    False
5    False
6     True
Name: Marks, dtype: bool

In [92]:
data[(data['Marks'] >= 90) & (data['Marks'] <= 100)]

      Name  Marks  Gender
0    abhay     90  Female
2   aayush     98    Male
6  anshika     96  Female

In [93]:
data[(data['Marks'] >= 90) & (data['Marks'] <= 100)]['Marks'].mean()

np.float64(94.66666666666667)

In [94]:
def marks(x):
    return x/2
print(marks(80))

40.0

In [95]:
data['Marks'].apply(marks)

0    45.0
1    39.0
2    49.0
3    44.5
4    43.5
5    44.0
6    48.0
Name: Marks, dtype: float64

In [96]:
data['Half Marks'] = data['Marks'].apply(marks)
data

      Name  Marks  Gender  Half Marks
0    abhay     90  Female        45.0
1   aastik     78  Female        39.0
2   aayush     98    Male        49.0
3  aayushi     89    Male        44.5
4    kohli     87    Male        43.5
5    begum     88    Male        44.0
6  anshika     96  Female        48.0

In [97]:
data['Marks'].apply(lambda x : x/2)

0    45.0
1    39.0
2    49.0
3    44.5
4    43.5
5    44.0
6    48.0
Name: Marks, dtype: float64

In [98]:
data['Name'].apply(len)

0    5
1    6
2    6
3    7
4    5
5    5
6    7
Name: Name, dtype: int64

In [99]:
# 17. map () function

In [100]:
data['Gender'].map({'Male': 1, 'Female': 2})

0    2
1    2
2    1
3    1
4    1
5    1
6    2
Name: Gender, dtype: int64

In [101]:
data['Male_Female'] = data['Gender'].map({'Male': 1, 'Female': 2})
data

      Name  Marks  Gender  Half Marks  Male_Female
0    abhay     90  Female        45.0            2
1   aastik     78  Female        39.0            2
2   aayush     98    Male        49.0            1
3  aayushi     89    Male        44.5            1
4    kohli     87    Male        43.5            1
5    begum     88    Male        44.0            1
6  anshika     96  Female        48.0            2

In [102]:
data.drop(['Half Marks', 'Male_Female'], axis=1, inplace=True)
data

C:\Users\arish\AppData\Local\Temp\ipykernel_28700\3041536351.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.drop(['Half Marks', 'Male_Female'], axis=1, inplace=True)

      Name  Marks  Gender
0    abhay     90  Female
1   aastik     78  Female
2   aayush     98    Male
3  aayushi     89    Male
4    kohli     87    Male
5    begum     88    Male
6  anshika     96  Female

In [103]:
data.columns

Index(['Name', 'Marks', 'Gender'], dtype='str')

In [104]:
data.index

RangeIndex(start=0, stop=7, step=1)

In [106]:
data.columns.tolist()

['Name', 'Marks', 'Gender']

In [108]:
data.sort_values(by = 'Marks', ascending = False)

      Name  Marks  Gender
2   aayush     98    Male
6  anshika     96  Female
0    abhay     90  Female
3  aayushi     89    Male
5    begum     88    Male
4    kohli     87    Male
1   aastik     78  Female

In [109]:
data[['Marks','Gender']]

   Marks  Gender
0     90  Female
1     78  Female
2     98    Male
3     89    Male
4     87    Male
5     88    Male
6     96  Female

In [110]:
data[data['Gender']=='Female'][['Name', 'Marks', 'Gender']]

      Name  Marks  Gender
0    abhay     90  Female
1   aastik     78  Female
6  anshika     96  Female

In [111]:
data[data['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
0    abhay     90
1   aastik     78
6  anshika     96